setwd("D:/renji/ILD")
library(DynNom)
library(rsconnect)
library(PKI)
library(survival)
library(openxlsx)
data1<-read.xlsx("clinicaltable.xlsx",sheet=1)
data1$FVC.rate<-factor(data1$FVC.rate,order=FALSE,levels=c('0','1','2'))
data1$result<-as.numeric(as.character(data1$result))
data1$survival.time<-as.numeric(as.character(data1$survival.time))
train<-subset(data1,train==1)
CRmodel<-coxph(Surv(survival.time,result)~radscore+age+FVC.rate,train)
DynNom(CRmodel,train)
DNbuilder(CRmodel, data = train, clevel = 0.95, m.summary = c("raw"), covariate = c("slider"), ptype = c("st"))
rsconnect::setAccountInfo(name='mda5-ild', token='53E8BB61F03351AA221F01C8DF69FF02', secret='P7ErLM7BvxavoQ2pbbLKU5ECDMULZ1Aea0tFLx2F')
library(shiny)
runApp("DynNomapp")
rsconnect::deployApp("D:/renji/ILD/DynNomapp")
